#!/bin/bash
#this backs up a database

EXPECTED_ARGS=3
E_BADARGS=65

TIMESTAMP=$( date +'%m_%d_%Y' )
FILENAME="mysql.bkup.$TIMESTAMP.sql"
DIRECTORY="$3"
FILEDEST="$DIRECTORY/$2.$FILENAME"

mysqldump -u$1 -p $2 > $FILEDEST

if [ $# -ne $EXPECTED_ARGS ]
    then
        echo "Usage: $0 username dbname destination"
        exit $E_BADARGS
fi
